controller_manager_ns: controller_manager
controller_list:
 - name: manipulator/shoulder_slider_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints: 
    - shoulder_slider

 - name: manipulator/left_arm_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints: 
    - elbow_pitch_joint
    - shoulder_pitch_joint
    - shoulder_roll_joint
    - wrist_pitch_joint
    - wrist_roll_joint
    - wrist_yaw_joint
