controller_manager_ns: ''
controller_list:
  - name: manipulator/left_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - shoulder_pitch_joint
      - elbow_pitch_joint
      - wrist_pitch_joint
      - wrist_yaw_joint
      - wrist_roll_joint
