controller_list:
  - name: fake_manipulator_controller
    joints:
      - shoulder_roll_joint
      - shoulder_pitch_joint
      - elbow_pitch_joint
      - wrist_pitch_joint
      - wrist_yaw_joint
      - wrist_roll_joint